936: Create an endpoint that allows querying of team assignment using…
opensrp/opensrp-server-web pull request #950
Opened 2021-09-21 18:23 UTC by rehammuzzamil

… the practitioner Identifier

#936

2021-09-21 23:34 UTC, dubdabasoduba requested changes
- Update the server web versions 
- Add the server code dependencies
- Also update the [v2.2 branch](https://github.com/opensrp/opensrp-server-web/tree/v2.2) with the same changes.

2021-09-21 23:34 UTC, dubdabasoduba commented on src/main/java/org/opensrp/web/rest/OrganizationResource.java
> +	@GetMapping(value = "/by-practitioner/{practitioner-identifier}", produces = { MediaType.APPLICATION_JSON_VALUE })
Please add a java doc for this.

2021-09-24 14:16 UTC, rehammuzzamil commented on src/main/java/org/opensrp/web/rest/OrganizationResource.java
> +	@GetMapping(value = "/by-practitioner/{practitioner-identifier}", produces = { MediaType.APPLICATION_JSON_VALUE })
Added. Thanks

2021-10-04 07:47 UTC, dubdabasoduba approved these changes

2021-10-04 07:49 UTC, merged